[package]
name = "fragtk"
version = "1.7.0"
edition = "2021"
authors = ["Tim Stuart <stuartt@a-star.edu.sg>"]
description = "Fragment file toolkit"
license = "MIT"
repository = "https://github.com/stuart-lab/fragtk"
documentation = "https://crates.io/crates/fragtk"
readme = "README.md"

[dependencies]
clap = { version = "4.1", features = ["derive"] }
flate2 = { version = "1.0.30", features = ["zlib-ng"], default-features = false }
gzp = "1.0.1"
log = "0.4.22"
pretty_env_logger = "0.5.0"
rust-lapper = "1.1.0"
rustc-hash = "2.0.0"
clap_mangen = "0.2"
smallvec = "1.15.0"
lexical-core = "1.0.5"
itoa = "1.0"
tempfile = "3.19.1"
bio = "2.3.0"
bio-types = "1.0.4"
hdf5 = { version = "0.8.1", optional = true }
ndarray = { version = "0.15.6", optional = true }

[features]
hdf5 = ["dep:hdf5", "dep:ndarray"]

[target.'cfg(not(target_os = "windows"))'.dependencies]
tikv-jemallocator = "0.6.0"

[profile.release]
panic = "abort"

[[bin]]
name = "fragtk"
path = "src/main.rs"
